"""Output Formatter — generates Markdown and JSON triage reports."""

import json
import logging
from datetime import datetime, timezone
from .models import IoCType, RiskLevel, TriageReport

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Risk level emoji / styling
# ---------------------------------------------------------------------------

RISK_EMOJI = {
    RiskLevel.NONE: "⚪",
    RiskLevel.LOW: "🟢",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.HIGH: "🟠",
    RiskLevel.CRITICAL: "🔴",
}

RISK_BAR = {
    RiskLevel.NONE: "⬜⬜⬜⬜⬜  NONE",
    RiskLevel.LOW: "🟩⬜⬜⬜⬜  LOW",
    RiskLevel.MEDIUM: "🟩🟨⬜⬜⬜  MEDIUM",
    RiskLevel.HIGH: "🟩🟨🟧⬜⬜  HIGH",
    RiskLevel.CRITICAL: "🟩🟨🟧🟥⬜  CRITICAL",
}

IOC_LABEL = {
    IoCType.IPV4: "IPv4",
    IoCType.DOMAIN: "Domain",
    IoCType.MD5: "MD5",
    IoCType.SHA256: "SHA256",
}


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------


def format_markdown(report: TriageReport, source_text: str | None = None) -> str:
    """Generate a clean Markdown triage report.

    Args:
        report: The scored TriageReport.
        source_text: Optional snippet of the original log for context.

    Returns:
        Markdown-formatted string.
    """
    lines: list[str] = []

    # Header
    lines.append("# 🛡️ MINOS Triage Report")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append("")

    # Overall risk
    overall_label = RISK_BAR.get(report.overall_risk, "UNKNOWN")
    lines.append("## Overall Risk Assessment")
    lines.append("")
    lines.append(f"| Risk Level |")
    lines.append(f"| --- |")
    lines.append(f"| {overall_label} |")
    lines.append("")

    # Summary stats
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"| --- | --- |")
    lines.append(f"| Total IoCs Extracted | {report.total_iocs} |")
    lines.append(f"| Unique IoCs | {report.unique_iocs} |")
    lines.append(f"| Overall Risk | {RISK_EMOJI.get(report.overall_risk, '⚪')} **{report.overall_risk.value.upper()}** |")
    lines.append("")

    # IoC Details Table
    if report.iocs:
        lines.append("## Indicators of Compromise (IoCs)")
        lines.append("")
        lines.append("| Type | Value | Risk Level | Sources |")
        lines.append("| --- | --- | --- | --- |")
        for ioc in report.iocs:
            emoji = RISK_EMOJI.get(ioc.risk_level, "⚪")
            ioc_type = IOC_LABEL.get(ioc.ioc_type, ioc.ioc_type.value)
            sources = ", ".join(ioc.sources) if ioc.sources else "—"
            lines.append(
                f"| {ioc_type} | `{ioc.value}` | {emoji} {ioc.risk_level.value.upper()} | {sources} |"
            )
        lines.append("")

    # Threat Intel Results
    if report.results:
        lines.append("## Threat Intelligence Results")
        lines.append("")
        lines.append("| IoC | Source | Confidence | Verdict |")
        lines.append("| --- | --- | --- | --- |")
        for r in report.results:
            conf = f"{r.confidence_score:.1f}%" if not r.error else f"⚠️ {r.error}"
            verdict = (
                f"{r.malicious_count}/{r.total_count} malicious"
                if r.source == "VirusTotal"
                else f"{r.malicious_count} reports"
                if r.source == "AbuseIPDB"
                else "—"
            )
            lines.append(f"| `{r.ioc.value}` | {r.source} | {conf} | {verdict} |")
        lines.append("")

    # Source log snippet
    if source_text:
        lines.append("## Source Log")
        lines.append("")
        lines.append("```")
        # Limit snippet to 500 chars
        snippet = source_text[:500]
        if len(source_text) > 500:
            snippet += "\n... (truncated)"
        lines.append(snippet)
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("*Report generated by MINOS — Auto-Triage SOC Bot*")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON report (SIEM-ingestible)
# ---------------------------------------------------------------------------


def format_json(report: TriageReport, pretty: bool = True) -> str:
    """Generate a JSON representation of the triage report.

    Args:
        report: The scored TriageReport.
        pretty: If True (default), pretty-print with indentation.

    Returns:
        JSON string.
    """
    iocs_json = [
        {
            "type": ioc.ioc_type.value,
            "value": ioc.value,
            "risk_level": ioc.risk_level.value,
            "sources": ioc.sources,
        }
        for ioc in report.iocs
    ]

    results_json = [
        {
            "ioc": {
                "type": r.ioc.ioc_type.value,
                "value": r.ioc.value,
            },
            "source": r.source,
            "malicious_count": r.malicious_count,
            "total_count": r.total_count,
            "confidence_score": round(r.confidence_score, 2),
            "error": r.error,
        }
        for r in report.results
    ]

    output = {
        "report": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "overall_risk": report.overall_risk.value,
            "total_iocs": report.total_iocs,
            "unique_iocs": report.unique_iocs,
        },
        "iocs": iocs_json,
        "threat_intel_results": results_json,
    }

    indent = 2 if pretty else None
    return json.dumps(output, indent=indent, ensure_ascii=False)
