import { useRef } from "react";
import { IoC, IoCType, RiskLevel, ThreatIntelResult } from "../types";

interface Props {
  iocs: IoC[];
  results: ThreatIntelResult[];
  overallRisk: RiskLevel;
}

const TYPE_LABEL: Record<IoCType, string> = {
  [IoCType.IPV4]: "IPv4",
  [IoCType.DOMAIN]: "Domain",
  [IoCType.MD5]: "MD5",
  [IoCType.SHA256]: "SHA256",
};

function buildJsonReport(props: Props) {
  return {
    report: {
      generated_at: new Date().toISOString(),
      overall_risk: props.overallRisk,
      total_iocs: props.iocs.length,
      unique_iocs: props.iocs.length,
    },
    iocs: props.iocs.map((i) => ({
      type: i.type,
      value: i.value,
      risk_level: i.riskLevel,
      sources: i.sources,
    })),
    threat_intel_results: props.results.map((r) => ({
      ioc: { type: r.ioc.type, value: r.ioc.value },
      source: r.source,
      malicious_count: r.maliciousCount,
      total_count: r.totalCount,
      confidence_score: r.confidenceScore,
      error: r.error,
    })),
  };
}

function buildMarkdown(props: Props): string {
  const lines: string[] = [
    "# 🛡️ MINOS Triage Report",
    "",
    `**Generated:** ${new Date().toISOString()}`,
    "",
    "## Overall Risk Assessment",
    "",
    `| Risk Level |\n| --- |\n| **${props.overallRisk.toUpperCase()}** |`,
    "",
    "## Indicators of Compromise (IoCs)",
    "",
    "| Type | Value | Risk Level | Sources |",
    "| --- | --- | --- | --- |",
  ];

  for (const ioc of props.iocs) {
    lines.push(
      `| ${TYPE_LABEL[ioc.type]} | \`${ioc.value}\` | ${ioc.riskLevel.toUpperCase()} | ${ioc.sources.join(", ") || "—"} |`,
    );
  }

  if (props.results.length > 0) {
    lines.push("", "## Threat Intelligence Results", "", "| IoC | Source | Confidence | Verdict |", "| --- | --- | --- | --- |");
    for (const r of props.results) {
      const verdict = r.error
        ? `⚠ ${r.error}`
        : r.source === "VirusTotal"
          ? `${r.maliciousCount}/${r.totalCount} malicious`
          : `${r.maliciousCount} reports`;
      lines.push(`| \`${r.ioc.value}\` | ${r.source} | ${r.error ? "—" : `${r.confidenceScore.toFixed(1)}%`} | ${verdict} |`);
    }
  }

  lines.push("", "---", "*Report generated by MINOS — Auto-Triage SOC Bot*");
  return lines.join("\n");
}

function download(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ExportButton(props: Props) {
  const btnRef = useRef<HTMLButtonElement>(null);

  const copyJson = async () => {
    const json = JSON.stringify(buildJsonReport(props), null, 2);
    await navigator.clipboard.writeText(json);
    if (btnRef.current) btnRef.current.textContent = "Copied!";
    setTimeout(() => { if (btnRef.current) btnRef.current.textContent = "Copy JSON"; }, 2000);
  };

  if (props.iocs.length === 0) return null;

  return (
    <div style={{ display: "flex", gap: "0.5rem", marginBottom: "1.5rem" }}>
      <button ref={btnRef} onClick={copyJson}>Copy JSON</button>
      <button onClick={() => download(JSON.stringify(buildJsonReport(props), null, 2), "minos-report.json", "application/json")}>
        Download .json
      </button>
      <button onClick={() => download(buildMarkdown(props), "minos-report.md", "text/markdown")}>
        Download .md
      </button>
    </div>
  );
}
